%% Import data from text file.
% Script for importing data from the following text file:
%
%    X:\tomas\Documents\BNL\2018-1\maxs\analysis\linecut_angle\SpinA_MEG_NA_th0.220_10.00s_330678_maxs.dat
%
% To extend the code to different selected data or a different text file,
% generate a function instead of a script.

% Auto-generated by MATLAB on 2018/08/27 22:37:52

%% Initialize variables.
filename = './SpinD_NoMEG_NA_th0.220_10.00s_331728_maxs.dat';
delimiter = ' ';
startRow = 2;

%% Format for each line of text:
%   column1: double (%f)
%	column2: double (%f)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%f%f%*s%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to the format.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, 'Delimiter', delimiter, 'MultipleDelimsAsOne', true, 'TextType', 'string', 'HeaderLines' ,startRow-1, 'ReturnOnError', false, 'EndOfLine', '\r\n');

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Create output variable
SpinD_noMEG_NA = table(dataArray{1:end-1}, 'VariableNames', {'chi','I'});

%% Clear temporary variables
clearvars filename delimiter startRow formatSpec fileID dataArray ans;